import { Calculator } from './calculators/types';
import { mathCalculators } from './calculators/math';
import { electricCalculators } from './calculators/electric';
import { otherCalculators } from './calculators/others';

export type { Calculator };

export function getAllCalculators(): Calculator[] {
  return [
    ...mathCalculators,
    ...electricCalculators,
    ...otherCalculators,
  ];
}

// Export individual calculator arrays for use in category pages
export { mathCalculators, electricCalculators, otherCalculators };
    // Math Calculators
    {
      id: 'addition',
      titleKey: 'addition.title',
      descKey: 'addition.description',
      path: '/calculators/math/addition',
      category: 'math',
    },
    {
      id: 'adding-fractions',
      titleKey: 'addingFractions.title',
      descKey: 'addingFractions.description',
      path: '/calculators/math/adding-fractions',
      category: 'math',
    },
    {
      id: 'antilog',
      titleKey: 'antilog.title',
      descKey: 'antilog.description',
      path: '/calculators/math/antilog',
      category: 'math',
    },
    {
      id: 'arccos',
      titleKey: 'arccos.title',
      descKey: 'arccos.description',
      path: '/calculators/math/arccos',
      category: 'math',
    },
    {
      id: 'arcsin',
      titleKey: 'arcsin.title',
      descKey: 'arcsin.description',
      path: '/calculators/math/arcsin',
      category: 'math',
    },
    {
      id: 'arctan',
      titleKey: 'arctan.title',
      descKey: 'arctan.description',
      path: '/calculators/math/arctan',
      category: 'math',
    },
    {
      id: 'average',
      titleKey: 'average.title',
      descKey: 'average.description',
      path: '/calculators/math/average',
      category: 'math',
    },
    {
      id: 'percentage',
      titleKey: 'percentage.title',
      descKey: 'percentage.description',
      path: '/calculators/math/percentage',
      category: 'math',
    },
    // Electric Calculators
    {
      id: 'watts-to-kva',
      titleKey: 'wattsToKva.title',
      descKey: 'wattsToKva.description',
      path: '/calculators/electric/watts-to-kva',
      category: 'electric',
    },
    {
      id: 'watts-to-va',
      titleKey: 'wattsToVa.title',
      descKey: 'wattsToVa.description',
      path: '/calculators/electric/watts-to-va',
      category: 'electric',
    },
    {
      id: 'amp-to-kw',
      titleKey: 'ampToKw.title',
      descKey: 'ampToKw.description',
      path: '/calculators/electric/amp-to-kw',
      category: 'electric',
    },
    {
      id: 'kw-to-amps',
      titleKey: 'kwToAmps.title',
      descKey: 'kwToAmps.description',
      path: '/calculators/electric/kw-to-amps',
      category: 'electric',
    },
    {
      id: 'kw-to-volts',
      titleKey: 'kwToVolts.title',
      descKey: 'kwToVolts.description',
      path: '/calculators/electric/kw-to-volts',
      category: 'electric',
    },
    {
      id: 'kw-to-kwh',
      titleKey: 'kwToKwh.title',
      descKey: 'kwToKwh.description',
      path: '/calculators/electric/kw-to-kwh',
      category: 'electric',
    },
    {
      id: 'kwh-to-kw',
      titleKey: 'kwhToKw.title',
      descKey: 'kwhToKw.description',
      path: '/calculators/electric/kwh-to-kw',
      category: 'electric',
    },
    {
      id: 'kw-to-va',
      titleKey: 'kwToVa.title',
      descKey: 'kwToVa.description',
      path: '/calculators/electric/kw-to-va',
      category: 'electric',
    },
    {
      id: 'kw-to-kva',
      titleKey: 'kwToKva.title',
      descKey: 'kwToKva.description',
      path: '/calculators/electric/kw-to-kva',
      category: 'electric',
    },
    {
      id: 'kwh-to-watts',
      titleKey: 'kwhToWatts.title',
      descKey: 'kwhToWatts.description',
      path: '/calculators/electric/kwh-to-watts',
      category: 'electric',
    },
    {
      id: 'mah-to-wh',
      titleKey: 'mahToWh.title',
      descKey: 'mahToWh.description',
      path: '/calculators/electric/mah-to-wh',
      category: 'electric',
    },
    {
      id: 'wh-to-mah',
      titleKey: 'whToMah.title',
      descKey: 'whToMah.description',
      path: '/calculators/electric/wh-to-mah',
      category: 'electric',
    },
    {
      id: 'va-to-amps',
      titleKey: 'vaToAmps.title',
      descKey: 'vaToAmps.description',
      path: '/calculators/electric/va-to-amps',
      category: 'electric',
    },
    {
      id: 'va-to-watts',
      titleKey: 'vaToWatts.title',
      descKey: 'vaToWatts.description',
      path: '/calculators/electric/va-to-watts',
      category: 'electric',
    },
    {
      id: 'va-to-kw',
      titleKey: 'vaToKw.title',
      descKey: 'vaToKw.description',
      path: '/calculators/electric/va-to-kw',
      category: 'electric',
    },
    {
      id: 'va-to-kva',
      titleKey: 'vaToKva.title',
      descKey: 'vaToKva.description',
      path: '/calculators/electric/va-to-kva',
      category: 'electric',
    },
    {
      id: 'amp-to-kva',
      titleKey: 'ampToKva.title',
      descKey: 'ampToKva.description',
      path: '/calculators/electric/amp-to-kva',
      category: 'electric',
    },
    {
      id: 'amps-to-va',
      titleKey: 'ampToVa.title',
      descKey: 'ampToVa.description',
      path: '/calculators/electric/amps-to-va',
      category: 'electric',
    },
    {
      id: 'amps-to-volt',
      titleKey: 'ampsToVolt.title',
      descKey: 'ampsToVolt.description',
      path: '/calculators/electric/amps-to-volt',
      category: 'electric',
    },
    {
      id: 'volts-to-amps',
      titleKey: 'voltsToAmps.title',
      descKey: 'voltsToAmps.description',
      path: '/calculators/electric/volts-to-amps',
      category: 'electric',
    },
    {
      id: 'volts-to-watts',
      titleKey: 'voltsToWatts.title',
      descKey: 'voltsToWatts.description',
      path: '/calculators/electric/volts-to-watts',
      category: 'electric',
    },
    {
      id: 'volts-to-kw',
      titleKey: 'voltsToKw.title',
      descKey: 'voltsToKw.description',
      path: '/calculators/electric/volts-to-kw',
      category: 'electric',
    },
    {
      id: 'amps-to-watts',
      titleKey: 'ampsToWatts.title',
      descKey: 'ampsToWatts.description',
      path: '/calculators/electric/amps-to-watts',
      category: 'electric',
    },
    {
      id: 'watts-to-amps',
      titleKey: 'wattsToAmps.title',
      descKey: 'wattsToAmps.description',
      path: '/calculators/electric/watts-to-amps',
      category: 'electric',
    },
    {
      id: 'electron-volts-to-volts',
      titleKey: 'electronVoltsToVolts.title',
      descKey: 'electronVoltsToVolts.description',
      path: '/calculators/electric/electron-volts-to-volts',
      category: 'electric',
    },
    {
      id: 'volts-to-electron-volts',
      titleKey: 'voltsToElectronVolts.title',
      descKey: 'voltsToElectronVolts.description',
      path: '/calculators/electric/volts-to-electron-volts',
      category: 'electric',
    },
    {
      id: 'joules-to-watts',
      titleKey: 'joulesToWatts.title',
      descKey: 'joulesToWatts.description',
      path: '/calculators/electric/joules-to-watts',
      category: 'electric',
    },
    {
      id: 'watts-to-joules',
      titleKey: 'wattsToJoules.title',
      descKey: 'wattsToJoules.description',
      path: '/calculators/electric/watts-to-joules',
      category: 'electric',
    },
    {
      id: 'watts-to-kwh',
      titleKey: 'wattsToKwh.title',
      descKey: 'wattsToKwh.description',
      path: '/calculators/electric/watts-to-kwh',
      category: 'electric',
    },
    {
      id: 'watts-to-volts',
      titleKey: 'wattsToVolts.title',
      descKey: 'wattsToVolts.description',
      path: '/calculators/electric/watts-to-volts',
      category: 'electric',
    },
    {
      id: 'joules-to-volts',
      titleKey: 'joulesToVolts.title',
      descKey: 'joulesToVolts.description',
      path: '/calculators/electric/joules-to-volts',
      category: 'electric',
    },
    {
      id: 'volts-to-joules',
      titleKey: 'voltsToJoules.title',
      descKey: 'voltsToJoules.description',
      path: '/calculators/electric/volts-to-joules',
      category: 'electric',
    },
    {
      id: 'kva-to-amps',
      titleKey: 'kvaToAmps.title',
      descKey: 'kvaToAmps.description',
      path: '/calculators/electric/kva-to-amps',
      category: 'electric',
    },
    {
      id: 'kva-to-watts',
      titleKey: 'kvaToWatts.title',
      descKey: 'kvaToWatts.description',
      path: '/calculators/electric/kva-to-watts',
      category: 'electric',
    },
    {
      id: 'kva-to-kw',
      titleKey: 'kvaToKw.title',
      descKey: 'kvaToKw.description',
      path: '/calculators/electric/kva-to-kw',
      category: 'electric',
    },
    {
      id: 'kva-to-va',
      titleKey: 'kvaToVa.title',
      descKey: 'kvaToVa.description',
      path: '/calculators/electric/kva-to-va',
      category: 'electric',
    },
    // Other Calculators
    {
      id: 'text-to-binary',
      titleKey: 'textToBinary.title',
      descKey: 'textToBinary.description',
      path: '/calculators/others/text-to-binary',
      category: 'others',
    },
    {
      id: 'ascii-converter',
      titleKey: 'asciiConverter.title',
      descKey: 'asciiConverter.description',
      path: '/calculators/others/ascii-converter',
      category: 'others',
    },
    {
      id: 'caesar-cipher',
      titleKey: 'caesarCipher.title',
      descKey: 'caesarCipher.description',
      path: '/calculators/others/caesar-cipher',
      category: 'others',
    },
    {
      id: 'pig-latin',
      titleKey: 'pigLatin.title',
      descKey: 'pigLatin.description',
      path: '/calculators/others/pig-latin',
      category: 'others',
    },
    {
      id: 'bold-text',
      titleKey: 'boldText.title',
      descKey: 'boldText.description',
      path: '/calculators/others/bold-text',
      category: 'others',
    },
    {
      id: 'small-caps',
      titleKey: 'smallCaps.title',
      descKey: 'smallCaps.description',
      path: '/calculators/others/small-caps',
      category: 'others',
    },
    {
      id: 'mirror-text',
      titleKey: 'mirrorText.title',
      descKey: 'mirrorText.description',
      path: '/calculators/others/mirror-text',
      category: 'others',
    },
    {
      id: 'nato-phonetic',
      titleKey: 'natoPhonetic.title',
      descKey: 'natoPhonetic.description',
      path: '/calculators/others/nato-phonetic',
      category: 'others',
    },
    {
      id: 'numbers-to-letters',
      titleKey: 'numbersToLetters.title',
      descKey: 'numbersToLetters.description',
      path: '/calculators/others/numbers-to-letters',
      category: 'others',
    },
    {
      id: 'letters-to-numbers',
      titleKey: 'lettersToNumbers.title',
      descKey: 'lettersToNumbers.description',
      path: '/calculators/others/letters-to-numbers',
      category: 'others',
    },
    {
      id: 'italic-text',
      titleKey: 'italicText.title',
      descKey: 'italicText.description',
      path: '/calculators/others/italic-text',
      category: 'others',
    },
    {
      id: 'upside-down-text',
      titleKey: 'upsideDownText.title',
      descKey: 'upsideDownText.description',
      path: '/calculators/others/upside-down-text',
      category: 'others',
    },
    {
      id: 'dna-to-mrna',
      titleKey: 'dnaToMrna.title',
      descKey: 'dnaToMrna.description',
      path: '/calculators/others/dna-to-mrna',
      category: 'others',
    },
  ];
}
