/**
 * Default calculator labels per locale for admin-created calculators.
 * Used when the Calculator labels field is empty — shows locale-appropriate example and defaults.
 */
import { routing } from '@/i18n/routing';

const LABELS: Record<string, Record<string, string>> = {
  en: {
    calculate: 'Calculate',
    reset: 'Reset',
    result: 'Result',
    resultFraction: 'Result (fraction)',
    resultDecimal: 'Result (decimal)',
    resultPlaceholder: 'Enter expression and click Calculate',
    title: 'Calculator',
    copy: 'Copy',
    copied: 'Copied!',
  },
  pl: {
    calculate: 'Oblicz',
    reset: 'Resetuj',
    result: 'Wynik',
    resultFraction: 'Wynik (ułamek)',
    resultDecimal: 'Wynik (dziesiętny)',
    resultPlaceholder: 'Wprowadź wyrażenie i kliknij Oblicz',
    title: 'Kalkulator',
    copy: 'Kopiuj',
    copied: 'Skopiowano!',
  },
  de: {
    calculate: 'Berechnen',
    reset: 'Zurücksetzen',
    result: 'Ergebnis',
    resultFraction: 'Ergebnis (Bruch)',
    resultDecimal: 'Ergebnis (Dezimal)',
    resultPlaceholder: 'Ausdruck eingeben und auf Berechnen klicken',
    title: 'Rechner',
    copy: 'Kopieren',
    copied: 'Kopiert!',
  },
  fr: {
    calculate: 'Calculer',
    reset: 'Réinitialiser',
    result: 'Résultat',
    resultFraction: 'Résultat (fraction)',
    resultDecimal: 'Résultat (décimal)',
    resultPlaceholder: 'Entrez une expression et cliquez sur Calculer',
    title: 'Calculatrice',
    copy: 'Copier',
    copied: 'Copié !',
  },
  es: {
    calculate: 'Calcular',
    reset: 'Restablecer',
    result: 'Resultado',
    resultFraction: 'Resultado (fracción)',
    resultDecimal: 'Resultado (decimal)',
    resultPlaceholder: 'Ingrese una expresión y haga clic en Calcular',
    title: 'Calculadora',
    copy: 'Copiar',
    copied: '¡Copiado!',
  },
  it: {
    calculate: 'Calcola',
    reset: 'Reimposta',
    result: 'Risultato',
    resultFraction: 'Risultato (frazione)',
    resultDecimal: 'Risultato (decimale)',
    resultPlaceholder: 'Inserisci un\'espressione e clicca Calcola',
    title: 'Calcolatrice',
    copy: 'Copia',
    copied: 'Copiato!',
  },
  nl: {
    calculate: 'Berekenen',
    reset: 'Resetten',
    result: 'Resultaat',
    resultFraction: 'Resultaat (breuk)',
    resultDecimal: 'Resultaat (decimaal)',
    resultPlaceholder: 'Voer een expressie in en klik op Berekenen',
    title: 'Rekenmachine',
    copy: 'Kopiëren',
    copied: 'Gekopieerd!',
  },
  pt: {
    calculate: 'Calcular',
    reset: 'Redefinir',
    result: 'Resultado',
    resultFraction: 'Resultado (fração)',
    resultDecimal: 'Resultado (decimal)',
    resultPlaceholder: 'Digite uma expressão e clique em Calcular',
    title: 'Calculadora',
    copy: 'Copiar',
    copied: 'Copiado!',
  },
  cs: {
    calculate: 'Vypočítat',
    reset: 'Resetovat',
    result: 'Výsledek',
    resultFraction: 'Výsledek (zlomek)',
    resultDecimal: 'Výsledek (desetinné)',
    resultPlaceholder: 'Zadejte výraz a klikněte na Vypočítat',
    title: 'Kalkulačka',
    copy: 'Kopírovat',
    copied: 'Zkopírováno!',
  },
  sk: {
    calculate: 'Vypočítať',
    reset: 'Resetovať',
    result: 'Výsledok',
    resultFraction: 'Výsledok (zlomok)',
    resultDecimal: 'Výsledok (desatinné)',
    resultPlaceholder: 'Zadajte výraz a kliknite na Vypočítať',
    title: 'Kalkulačka',
    copy: 'Kopírovať',
    copied: 'Skopírované!',
  },
  hu: {
    calculate: 'Számolás',
    reset: 'Alaphelyzet',
    result: 'Eredmény',
    resultFraction: 'Eredmény (tört)',
    resultDecimal: 'Eredmény (tizedes)',
    resultPlaceholder: 'Adja meg a kifejezést és kattintson a Számolásra',
    title: 'Számológép',
    copy: 'Másolás',
    copied: 'Másolva!',
  },
  sv: {
    calculate: 'Beräkna',
    reset: 'Återställ',
    result: 'Resultat',
    resultFraction: 'Resultat (bråk)',
    resultDecimal: 'Resultat (decimal)',
    resultPlaceholder: 'Ange ett uttryck och klicka på Beräkna',
    title: 'Kalkylator',
    copy: 'Kopiera',
    copied: 'Kopierat!',
  },
  no: {
    calculate: 'Beregn',
    reset: 'Tilbakestill',
    result: 'Resultat',
    resultFraction: 'Resultat (brøk)',
    resultDecimal: 'Resultat (desimal)',
    resultPlaceholder: 'Skriv inn et uttrykk og klikk på Beregn',
    title: 'Kalkulator',
    copy: 'Kopier',
    copied: 'Kopiert!',
  },
  da: {
    calculate: 'Beregn',
    reset: 'Nulstil',
    result: 'Resultat',
    resultFraction: 'Resultat (brøk)',
    resultDecimal: 'Resultat (decimal)',
    resultPlaceholder: 'Indtast et udtryk og klik på Beregn',
    title: 'Lommeregner',
    copy: 'Kopiér',
    copied: 'Kopieret!',
  },
  fi: {
    calculate: 'Laske',
    reset: 'Nollaa',
    result: 'Tulos',
    resultFraction: 'Tulos (murtoluku)',
    resultDecimal: 'Tulos (desimaali)',
    resultPlaceholder: 'Syötä lauseke ja napsauta Laske',
    title: 'Laskin',
    copy: 'Kopioi',
    copied: 'Kopioitu!',
  },
  ro: {
    calculate: 'Calculează',
    reset: 'Resetează',
    result: 'Rezultat',
    resultFraction: 'Rezultat (fracție)',
    resultDecimal: 'Rezultat (zecimal)',
    resultPlaceholder: 'Introduceți o expresie și faceți clic pe Calculează',
    title: 'Calculator',
    copy: 'Copiază',
    copied: 'Copiat!',
  },
  ru: {
    calculate: 'Рассчитать',
    reset: 'Сбросить',
    result: 'Результат',
    resultFraction: 'Результат (дробь)',
    resultDecimal: 'Результат (десятичный)',
    resultPlaceholder: 'Введите выражение и нажмите Рассчитать',
    title: 'Калькулятор',
    copy: 'Копировать',
    copied: 'Скопировано!',
  },
  ja: {
    calculate: '計算',
    reset: 'リセット',
    result: '結果',
    resultFraction: '結果（分数）',
    resultDecimal: '結果（小数）',
    resultPlaceholder: '式を入力して計算をクリック',
    title: '計算機',
    copy: 'コピー',
    copied: 'コピーしました!',
  },
  zh: {
    calculate: '计算',
    reset: '重置',
    result: '结果',
    resultFraction: '结果（分数）',
    resultDecimal: '结果（小数）',
    resultPlaceholder: '输入表达式并点击计算',
    title: '计算器',
    copy: '复制',
    copied: '已复制！',
  },
  ko: {
    calculate: '계산',
    reset: '초기화',
    result: '결과',
    resultFraction: '결과 (분수)',
    resultDecimal: '결과 (소수)',
    resultPlaceholder: '식을 입력하고 계산을 클릭하세요',
    title: '계산기',
    copy: '복사',
    copied: '복사됨!',
  },
  ar: {
    calculate: 'حساب',
    reset: 'إعادة تعيين',
    result: 'النتيجة',
    resultFraction: 'النتيجة (كسر)',
    resultDecimal: 'النتيجة (عشري)',
    resultPlaceholder: 'أدخل التعبير وانقر على حساب',
    title: 'آلة حاسبة',
    copy: 'نسخ',
    copied: 'تم النسخ!',
  },
  hi: {
    calculate: 'गणना करें',
    reset: 'रीसेट',
    result: 'परिणाम',
    resultFraction: 'परिणाम (भिन्न)',
    resultDecimal: 'परिणाम (दशमलव)',
    resultPlaceholder: 'अभिव्यक्ति दर्ज करें और गणना पर क्लिक करें',
    title: 'कैलकुलेटर',
    copy: 'कॉपी करें',
    copied: 'कॉपी हो गया!',
  },
  id: {
    calculate: 'Hitung',
    reset: 'Atur ulang',
    result: 'Hasil',
    resultFraction: 'Hasil (pecahan)',
    resultDecimal: 'Hasil (desimal)',
    resultPlaceholder: 'Masukkan ekspresi dan klik Hitung',
    title: 'Kalkulator',
    copy: 'Salin',
    copied: 'Disalin!',
  },
  tr: {
    calculate: 'Hesapla',
    reset: 'Sıfırla',
    result: 'Sonuç',
    resultFraction: 'Sonuç (kesir)',
    resultDecimal: 'Sonuç (ondalık)',
    resultPlaceholder: 'İfadeyi girin ve Hesapla\'ya tıklayın',
    title: 'Hesap Makinesi',
    copy: 'Kopyala',
    copied: 'Kopyalandı!',
  },
};

/** Default labels for a locale. Falls back to English if locale not found. */
export function getDefaultCalculatorLabels(locale: string): Record<string, string> {
  return LABELS[locale] ?? LABELS.en;
}

/** All locales that have default labels. */
export function getCalculatorLabelLocales(): string[] {
  return [...routing.locales];
}
