import express from 'express';
import { createQwikCity } from '@builder.io/qwik-city/middleware/node';
import { render } from './entry.ssr';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const app = express();

// Import qwikCityPlan - it should be generated by qwikCity() plugin
import qwikCityPlan from '@qwik-city-plan';

// Path to dist directory containing static files
// entry.express.js is in dist/, so distDir is the parent of __dirname
const distDir = __dirname;

console.log('📁 Dist directory:', distDir);

const { router, notFound, staticFile } = createQwikCity({
  render,
  qwikCityPlan,
  static: {
    root: distDir,
    cacheControl: 'public, max-age=31536000, immutable'
  }
});

// Use Express static middleware first for build/ and assets/ files
app.use(express.static(distDir, {
  maxAge: '1y',
  immutable: true
}));

// Then use Qwik City staticFile middleware
app.use(staticFile);

// Then handle Qwik routes
app.use(router);

// Finally handle 404
app.use(notFound);

app.listen(3000, '0.0.0.0', () => {
  console.log('✅ Qwik SSR running on http://0.0.0.0:3000');
  console.log('📁 Serving static files from:', distDir);
});
