import express from 'express';
import { createQwikCity } from '@builder.io/qwik-city/middleware/node';
import { render } from './entry.ssr';

const app = express();

// Import qwikCityPlan - it should be generated by qwikCity() plugin
import qwikCityPlan from '@qwik-city-plan';

const { router, notFound, staticFile } = createQwikCity({
  render,
  qwikCityPlan
});

// Serve static files first
app.use(staticFile);

// Then handle Qwik routes
app.use(router);

// Finally handle 404
app.use(notFound);

app.listen(3000, '0.0.0.0', () => {
  console.log('✅ Qwik SSR running on http://0.0.0.0:3000');
});
