import express from 'express';
import { createQwikCity } from '@builder.io/qwik-city/middleware/node';
import { render } from './entry.ssr';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { existsSync, readdirSync } from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const app = express();

// Import qwikCityPlan - it should be generated by qwikCity() plugin
import qwikCityPlan from '@qwik-city-plan';

// Path to dist directory containing static files
// entry.express.js is in dist/, so distDir is __dirname
const distDir = __dirname;

console.log('📁 Dist directory:', distDir);
console.log('📁 Checking if build/ exists:', existsSync(join(distDir, 'build')));
if (existsSync(join(distDir, 'build'))) {
  const buildFiles = readdirSync(join(distDir, 'build')).slice(0, 5);
  console.log('📁 Sample build files:', buildFiles);
  console.log('📁 preloader.js exists:', existsSync(join(distDir, 'build', 'preloader.js')));
}

// Error handling middleware
app.use((err, req, res, next) => {
  console.error('❌ Error serving:', req.path, err);
  res.status(500).send('Internal Server Error');
});

const { router, notFound, staticFile } = createQwikCity({
  render,
  qwikCityPlan,
  static: {
    root: distDir,
    cacheControl: 'public, max-age=31536000, immutable'
  }
});

// Use Express static middleware first for build/ and assets/ files
app.use(express.static(distDir, {
  maxAge: '1y',
  immutable: true
}));

// Log requests to build/ for debugging
app.use((req, res, next) => {
  if (req.path.startsWith('/build/')) {
    console.log('📦 Request for build file:', req.path);
  }
  next();
});

// Then use Qwik City staticFile middleware
app.use(staticFile);

// Then handle Qwik routes
app.use(router);

// Finally handle 404
app.use(notFound);

app.listen(3000, '0.0.0.0', () => {
  console.log('✅ Qwik SSR running on http://0.0.0.0:3000');
  console.log('📁 Serving static files from:', distDir);
});
