import { Calculator } from './types';

export const electricCalculators: Calculator[] = [
  {
    id: 'watts-to-kva',
    titleKey: 'wattsToKva.title',
    descKey: 'wattsToKva.description',
    path: '/calculators/electric/watts-to-kva',
    category: 'electric',
  },
  {
    id: 'watts-to-va',
    titleKey: 'wattsToVa.title',
    descKey: 'wattsToVa.description',
    path: '/calculators/electric/watts-to-va',
    category: 'electric',
  },
  {
    id: 'amp-to-kw',
    titleKey: 'ampToKw.title',
    descKey: 'ampToKw.description',
    path: '/calculators/electric/amp-to-kw',
    category: 'electric',
  },
  {
    id: 'kw-to-amps',
    titleKey: 'kwToAmps.title',
    descKey: 'kwToAmps.description',
    path: '/calculators/electric/kw-to-amps',
    category: 'electric',
  },
  {
    id: 'kw-to-volts',
    titleKey: 'kwToVolts.title',
    descKey: 'kwToVolts.description',
    path: '/calculators/electric/kw-to-volts',
    category: 'electric',
  },
  {
    id: 'kw-to-kwh',
    titleKey: 'kwToKwh.title',
    descKey: 'kwToKwh.description',
    path: '/calculators/electric/kw-to-kwh',
    category: 'electric',
  },
  {
    id: 'kwh-to-kw',
    titleKey: 'kwhToKw.title',
    descKey: 'kwhToKw.description',
    path: '/calculators/electric/kwh-to-kw',
    category: 'electric',
  },
  {
    id: 'kw-to-va',
    titleKey: 'kwToVa.title',
    descKey: 'kwToVa.description',
    path: '/calculators/electric/kw-to-va',
    category: 'electric',
  },
  {
    id: 'kw-to-kva',
    titleKey: 'kwToKva.title',
    descKey: 'kwToKva.description',
    path: '/calculators/electric/kw-to-kva',
    category: 'electric',
  },
  {
    id: 'kwh-to-watts',
    titleKey: 'kwhToWatts.title',
    descKey: 'kwhToWatts.description',
    path: '/calculators/electric/kwh-to-watts',
    category: 'electric',
  },
  {
    id: 'mah-to-wh',
    titleKey: 'mahToWh.title',
    descKey: 'mahToWh.description',
    path: '/calculators/electric/mah-to-wh',
    category: 'electric',
  },
  {
    id: 'wh-to-mah',
    titleKey: 'whToMah.title',
    descKey: 'whToMah.description',
    path: '/calculators/electric/wh-to-mah',
    category: 'electric',
  },
  {
    id: 'va-to-amps',
    titleKey: 'vaToAmps.title',
    descKey: 'vaToAmps.description',
    path: '/calculators/electric/va-to-amps',
    category: 'electric',
  },
  {
    id: 'va-to-watts',
    titleKey: 'vaToWatts.title',
    descKey: 'vaToWatts.description',
    path: '/calculators/electric/va-to-watts',
    category: 'electric',
  },
  {
    id: 'va-to-kw',
    titleKey: 'vaToKw.title',
    descKey: 'vaToKw.description',
    path: '/calculators/electric/va-to-kw',
    category: 'electric',
  },
  {
    id: 'va-to-kva',
    titleKey: 'vaToKva.title',
    descKey: 'vaToKva.description',
    path: '/calculators/electric/va-to-kva',
    category: 'electric',
  },
  {
    id: 'amp-to-kva',
    titleKey: 'ampToKva.title',
    descKey: 'ampToKva.description',
    path: '/calculators/electric/amp-to-kva',
    category: 'electric',
  },
  {
    id: 'amps-to-va',
    titleKey: 'ampToVa.title',
    descKey: 'ampToVa.description',
    path: '/calculators/electric/amps-to-va',
    category: 'electric',
  },
  {
    id: 'amps-to-volt',
    titleKey: 'ampsToVolt.title',
    descKey: 'ampsToVolt.description',
    path: '/calculators/electric/amps-to-volt',
    category: 'electric',
  },
  {
    id: 'volts-to-amps',
    titleKey: 'voltsToAmps.title',
    descKey: 'voltsToAmps.description',
    path: '/calculators/electric/volts-to-amps',
    category: 'electric',
  },
  {
    id: 'volts-to-watts',
    titleKey: 'voltsToWatts.title',
    descKey: 'voltsToWatts.description',
    path: '/calculators/electric/volts-to-watts',
    category: 'electric',
  },
  {
    id: 'volts-to-kw',
    titleKey: 'voltsToKw.title',
    descKey: 'voltsToKw.description',
    path: '/calculators/electric/volts-to-kw',
    category: 'electric',
  },
  {
    id: 'amps-to-watts',
    titleKey: 'ampsToWatts.title',
    descKey: 'ampsToWatts.description',
    path: '/calculators/electric/amps-to-watts',
    category: 'electric',
  },
  {
    id: 'watts-to-amps',
    titleKey: 'wattsToAmps.title',
    descKey: 'wattsToAmps.description',
    path: '/calculators/electric/watts-to-amps',
    category: 'electric',
  },
  {
    id: 'electron-volts-to-volts',
    titleKey: 'electronVoltsToVolts.title',
    descKey: 'electronVoltsToVolts.description',
    path: '/calculators/electric/electron-volts-to-volts',
    category: 'electric',
  },
  {
    id: 'volts-to-electron-volts',
    titleKey: 'voltsToElectronVolts.title',
    descKey: 'voltsToElectronVolts.description',
    path: '/calculators/electric/volts-to-electron-volts',
    category: 'electric',
  },
  {
    id: 'joules-to-watts',
    titleKey: 'joulesToWatts.title',
    descKey: 'joulesToWatts.description',
    path: '/calculators/electric/joules-to-watts',
    category: 'electric',
  },
  {
    id: 'watts-to-joules',
    titleKey: 'wattsToJoules.title',
    descKey: 'wattsToJoules.description',
    path: '/calculators/electric/watts-to-joules',
    category: 'electric',
  },
  {
    id: 'watts-to-kwh',
    titleKey: 'wattsToKwh.title',
    descKey: 'wattsToKwh.description',
    path: '/calculators/electric/watts-to-kwh',
    category: 'electric',
  },
  {
    id: 'watts-to-volts',
    titleKey: 'wattsToVolts.title',
    descKey: 'wattsToVolts.description',
    path: '/calculators/electric/watts-to-volts',
    category: 'electric',
  },
  {
    id: 'joules-to-volts',
    titleKey: 'joulesToVolts.title',
    descKey: 'joulesToVolts.description',
    path: '/calculators/electric/joules-to-volts',
    category: 'electric',
  },
  {
    id: 'volts-to-joules',
    titleKey: 'voltsToJoules.title',
    descKey: 'voltsToJoules.description',
    path: '/calculators/electric/volts-to-joules',
    category: 'electric',
  },
  {
    id: 'kva-to-amps',
    titleKey: 'kvaToAmps.title',
    descKey: 'kvaToAmps.description',
    path: '/calculators/electric/kva-to-amps',
    category: 'electric',
  },
  {
    id: 'kva-to-watts',
    titleKey: 'kvaToWatts.title',
    descKey: 'kvaToWatts.description',
    path: '/calculators/electric/kva-to-watts',
    category: 'electric',
  },
  {
    id: 'kva-to-kw',
    titleKey: 'kvaToKw.title',
    descKey: 'kvaToKw.description',
    path: '/calculators/electric/kva-to-kw',
    category: 'electric',
  },
  {
    id: 'kva-to-va',
    titleKey: 'kvaToVa.title',
    descKey: 'kvaToVa.description',
    path: '/calculators/electric/kva-to-va',
    category: 'electric',
  },
];
