import { Calculator, sortCalculatorsAlphabetically } from './types';

const mathCalculatorsList: Calculator[] = [
  {
    id: 'addition',
    titleKey: 'addition.title',
    descKey: 'addition.description',
    path: '/calculators/math/addition',
    category: 'math',
  },
  {
    id: 'adding-fractions',
    titleKey: 'addingFractions.title',
    descKey: 'addingFractions.description',
    path: '/calculators/math/adding-fractions',
    category: 'math',
  },
  {
    id: 'adding-subtracting-integers',
    titleKey: 'addingSubtractingIntegers.title',
    descKey: 'addingSubtractingIntegers.description',
    path: '/calculators/math/adding-subtracting-integers',
    category: 'math',
  },
  {
    id: 'subtracting-fractions',
    titleKey: 'subtractingFractions.title',
    descKey: 'subtractingFractions.description',
    path: '/calculators/math/subtracting-fractions',
    category: 'math',
  },
  {
    id: 'multiplying-fractions',
    titleKey: 'multiplyingFractions.title',
    descKey: 'multiplyingFractions.description',
    path: '/calculators/math/multiplying-fractions',
    category: 'math',
  },
  {
    id: 'natural-logarithm',
    titleKey: 'naturalLogarithm.title',
    descKey: 'naturalLogarithm.description',
    path: '/calculators/math/natural-logarithm',
    category: 'math',
  },
  {
    id: 'lcm',
    titleKey: 'lcm.title',
    descKey: 'lcm.description',
    path: '/calculators/math/lcm',
    category: 'math',
  },
  {
    id: 'gcf',
    titleKey: 'gcf.title',
    descKey: 'gcf.description',
    path: '/calculators/math/gcf',
    category: 'math',
  },
  {
    id: 'kinetic-energy',
    titleKey: 'kineticEnergy.title',
    descKey: 'kineticEnergy.description',
    path: '/calculators/math/kinetic-energy',
    category: 'math',
  },
  {
    id: 'antilog',
    titleKey: 'antilog.title',
    descKey: 'antilog.description',
    path: '/calculators/math/antilog',
    category: 'math',
  },
  {
    id: 'arccos',
    titleKey: 'arccos.title',
    descKey: 'arccos.description',
    path: '/calculators/math/arccos',
    category: 'math',
  },
  {
    id: 'cosine',
    titleKey: 'cosine.title',
    descKey: 'cosine.description',
    path: '/calculators/math/cosine',
    category: 'math',
  },
  {
    id: 'arcsin',
    titleKey: 'arcsin.title',
    descKey: 'arcsin.description',
    path: '/calculators/math/arcsin',
    category: 'math',
  },
  {
    id: 'arctan',
    titleKey: 'arctan.title',
    descKey: 'arctan.description',
    path: '/calculators/math/arctan',
    category: 'math',
  },
  {
    id: 'common-factors',
    titleKey: 'commonFactors.title',
    descKey: 'commonFactors.description',
    path: '/calculators/math/common-factors',
    category: 'math',
  },
  {
    id: 'average',
    titleKey: 'average.title',
    descKey: 'average.description',
    path: '/calculators/math/average',
    category: 'math',
  },
  {
    id: 'quadratic-equation',
    titleKey: 'quadraticEquation.title',
    descKey: 'quadraticEquation.description',
    path: '/calculators/math/quadratic-equation',
    category: 'math',
  },
  {
    id: 'pythagorean-theorem',
    titleKey: 'pythagoreanTheorem.title',
    descKey: 'pythagoreanTheorem.description',
    path: '/calculators/math/pythagorean-theorem',
    category: 'math',
  },
  {
    id: 'percentage',
    titleKey: 'percentage.title',
    descKey: 'percentage.description',
    path: '/calculators/math/percentage',
    category: 'math',
  },
  {
    id: 'percentage-increase',
    titleKey: 'percentageIncrease.title',
    descKey: 'percentageIncrease.description',
    path: '/calculators/math/percentage-increase',
    category: 'math',
  },
  {
    id: 'percent-error',
    titleKey: 'percentError.title',
    descKey: 'percentError.description',
    path: '/calculators/math/percent-error',
    category: 'math',
  },
  {
    id: 'ratio',
    titleKey: 'ratio.title',
    descKey: 'ratio.description',
    path: '/calculators/math/ratio',
    category: 'math',
  },
  {
    id: 'long-division',
    titleKey: 'longDivision.title',
    descKey: 'longDivision.description',
    path: '/calculators/math/long-division',
    category: 'math',
  },
  {
    id: 'long-multiplication',
    titleKey: 'longMultiplication.title',
    descKey: 'longMultiplication.description',
    path: '/calculators/math/long-multiplication',
    category: 'math',
  },
  {
    id: 'remainder',
    titleKey: 'remainder.title',
    descKey: 'remainder.description',
    path: '/calculators/math/remainder',
    category: 'math',
  },
  {
    id: 'polynomial-remainder',
    titleKey: 'polynomialRemainder.title',
    descKey: 'polynomialRemainder.description',
    path: '/calculators/math/polynomial-remainder',
    category: 'math',
  },
  {
    id: 'square-root',
    titleKey: 'squareRoot.title',
    descKey: 'squareRoot.description',
    path: '/calculators/math/square-root',
    category: 'math',
  },
  {
    id: 'convolution',
    titleKey: 'convolution.title',
    descKey: 'convolution.description',
    path: '/calculators/math/convolution',
    category: 'math',
  },
  {
    id: 'factorial',
    titleKey: 'factorial.title',
    descKey: 'factorial.description',
    path: '/calculators/math/factorial',
    category: 'math',
  },
  {
    id: 'sine',
    titleKey: 'sine.title',
    descKey: 'sine.description',
    path: '/calculators/math/sine',
    category: 'math',
  },
  {
    id: 'roots',
    titleKey: 'roots.title',
    descKey: 'roots.description',
    path: '/calculators/math/roots',
    category: 'math',
  },
];

export const mathCalculators: Calculator[] = sortCalculatorsAlphabetically(mathCalculatorsList);
