import { Calculator } from './types';

export const otherCalculators: Calculator[] = [
  {
    id: 'text-to-binary',
    titleKey: 'textToBinary.title',
    descKey: 'textToBinary.description',
    path: '/calculators/others/text-to-binary',
    category: 'others',
  },
  {
    id: 'square-root',
    titleKey: 'squareRoot.title',
    descKey: 'squareRoot.description',
    path: '/calculators/others/square-root',
    category: 'others',
  },
  {
    id: 'ascii-converter',
    titleKey: 'asciiConverter.title',
    descKey: 'asciiConverter.description',
    path: '/calculators/others/ascii-converter',
    category: 'others',
  },
  {
    id: 'caesar-cipher',
    titleKey: 'caesarCipher.title',
    descKey: 'caesarCipher.description',
    path: '/calculators/others/caesar-cipher',
    category: 'others',
  },
  {
    id: 'pig-latin',
    titleKey: 'pigLatin.title',
    descKey: 'pigLatin.description',
    path: '/calculators/others/pig-latin',
    category: 'others',
  },
  {
    id: 'bold-text',
    titleKey: 'boldText.title',
    descKey: 'boldText.description',
    path: '/calculators/others/bold-text',
    category: 'others',
  },
  {
    id: 'small-caps',
    titleKey: 'smallCaps.title',
    descKey: 'smallCaps.description',
    path: '/calculators/others/small-caps',
    category: 'others',
  },
  {
    id: 'mirror-text',
    titleKey: 'mirrorText.title',
    descKey: 'mirrorText.description',
    path: '/calculators/others/mirror-text',
    category: 'others',
  },
  {
    id: 'nato-phonetic',
    titleKey: 'natoPhonetic.title',
    descKey: 'natoPhonetic.description',
    path: '/calculators/others/nato-phonetic',
    category: 'others',
  },
  {
    id: 'numbers-to-letters',
    titleKey: 'numbersToLetters.title',
    descKey: 'numbersToLetters.description',
    path: '/calculators/others/numbers-to-letters',
    category: 'others',
  },
  {
    id: 'letters-to-numbers',
    titleKey: 'lettersToNumbers.title',
    descKey: 'lettersToNumbers.description',
    path: '/calculators/others/letters-to-numbers',
    category: 'others',
  },
  {
    id: 'italic-text',
    titleKey: 'italicText.title',
    descKey: 'italicText.description',
    path: '/calculators/others/italic-text',
    category: 'others',
  },
  {
    id: 'upside-down-text',
    titleKey: 'upsideDownText.title',
    descKey: 'upsideDownText.description',
    path: '/calculators/others/upside-down-text',
    category: 'others',
  },
];
